# Generated by Django 5.0.4 on 2024-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereg',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
